config/routes.rb
TreeBook2::Application.routes.draw do
  get "profiles/show"

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'edit', to: 'devise/registrations#edit', as: :edit
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => "devise/sessions#new", as: :new_user_session
    post "/login" => "devise/sessions#create", as: :user_session
    delete "/logout" => "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :user_friendships

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :user_id, :full_name, :first_name, :last_name

  validates :content, presence: true, length: { minimum: 2}

  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships, conditions: { user_friendships: { state: 'accepted' } }
  has_many :pending_user_friendships, class_name: 'UserFriendship', foreign_key: :user_id, conditions: { state: 'pending' }
  has_many :pending_friends, through: :pending_user_friendships, source: :friend
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :full_name, :profile_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


  validates:first_name, presence: true
  validates:last_name, presence: true
  validates:profile_name, presence: true, uniqueness: true,
  format: {
    with: /^[A-Za-z0-9\_]+$/,
    message: "Must be formatted correctly"
  }

  def full_name
    "#{first_name} #{last_name}"
  end

  def to_param
    profile_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  attr_accessible :user, :friend, :user_id, :friend_id, :state

  state_machine :state, initial: :pending do
    after_transition on: :accept, do: :send_acceptance_email

    state :requested

  	event :accept do
  		transition any => :accepted
  	end
  end

  def self.request(user1, user2)
    transaction do
      friendship1 = create(user: user1, friend: user2, state: 'pending')
      friendship2 = create(user: user2, friend: user1, state: 'requested')
      friendship1.send_request_email
      friendship1
    end
  end

  def send_request_email
  	UserNotifier.friend_requested(id).deliver
  end

  def send_acceptance_email
  	UserNotifier.friend_request_accepted(id).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])
    @status.user = current_user
    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end
    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
	before_filter :authenticate_user!

  def index
    @user_friendships = current_user.user_friendship.all
  end

  def accept
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.accept!
      flash[:success] = "You are now friends with #{user_friendship.friend.first_name}"
    else
      flash[:error] = "That friendship could not be accepted"
    end
    redirect_to user_friendships_path
  end
	
  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
      raise ActiveRecord::RecordNotFound if @friend.nil?
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] = "Friend Required"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

  def create
  	if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
  		@friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
  		@user_friendship = current_user.user_friendships.new(friend: @friend)
  		@user_friendship.save
  		flash[:success] = "You are now friends with #{@friend.full_name}"
  		redirect_to profile_path(@friend)
  	else
  		flash[:error] = "Friend Required"
  		redirect_to root_path
  	end
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a href="#" class="brand">Treebook</a>
			<ul class="nav">
				<li><%= link_to "All Statuses", statuses_path %></li>
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
					<li><%= link_to current_user.full_name, edit_path %></li>
					<li><%= link_to "Log Out", logout_path %></li>
				<% else %>
					<li><%= link_to "Register", register_path %></li>
					<li><%= link_to "Log In", login_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>
<div class="container">
	<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %>">
			<button class="close" data-dismiss="alert">x</button>
			<%= message %>
		</div>
	<% end %>
	<%= yield %>
</div>
<br><br>

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
	<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn' %>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
	<div class="well">
		<%= status.content %>
		<hr />
		<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
	</div>
	<% end %>
	<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :content %><br />
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
<h1>All Statuses</h1>
</div>

<%= link_to "Post a Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
<div class="status">
	<div class="row"
	<div class="span1">
		<%= link_to image_tag(status.user.gravatar_url), profile_path(status.user) %>
	</div>
	<div clas="span7">
  		<strong><%= status.user.full_name %></strong>
 		<p><%= status.content %></p>
  		<div class="meta">
    		<%= link_to time_ago_in_words(status.created_at) + " ago", status %>
    		<span class="admin">
      		| <%= link_to "Edit", edit_status_path(status) %> | 
        	<%= link_to "Delete", status, method: :delete, data: { confirm: "Delete?" } %>
     		</span>
  		</div>
	</div>
</div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/user_friendships/index.html.erb
<div class="page-header">
  <h1>Friends</h1>
</div>

<div>
  <strong>Friend list:</strong>
  <%= link_to 'Blocked', user_friendships_path(list: 'blocked') %>
  <%= link_to 'Requested', user_friendships_path(list: 'requested') %>
  <%= link_to 'Accepted', user_friendships_path(list: 'accepted') %>
  <%= link_to 'Pending', user_friendships_path(list: 'pending') %>
</div>

<% @user_friendships.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="friend row">
    <div class="span1">
      <%= link_to image_tag(friend.gravatar_url), profile_path(friend) %>
    </div>
    <div class="span7">
      <strong><%= friend.full_name %></strong><br />
        <% if friendship.pending? %>
          <em>Friendship is pending.</em> <%= link_to "Delete request", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end %>
        <% if friendship.requested? %>
          <em>Friendship requested.</em> <%= link_to "Accept Friendship", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end %>
        <% if friendship.accepted? %>
          <em>Friendship started <%= friendship.updated_at %>.</em> <%= link_to "Update friendship", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end %>
    </div>
  </div>
<% end %>

app/views/user_friendships/new.html.erb
<% if @friend %>
<h3><%= @friend.full_name %></h3>

<p>Confirm Friend Request for <%= @friend.full_name %></p>

  <%= form_for @user_friendship, method: :post do |form| %>
    <div class="form form-actions">
      <%= form.hidden_field :friend_id, value: @friend.profile_name %>
      <%= submit_tag "Yes, Add Friend", class: 'btn btn-primary' %>
      <%= link_to "Cancel", profile_path(@friend), class: 'btn' %>
    </div>
  <% end %>
<% end %>

app/views/user_notifier/friend_request_accepted.html.erb
Hi <%= @user.first_name %>!

Great news! <%= @friend.first_name %> has accepted your friend request. How awesome is that?

Have Fun!

app/views/user_notifier/friend_requested.html.erb
Hi <%= @friend.first_name %>,

<%= @user.first_name %> wants to be friends on Treebook. Isn't that great?

Love,
Mike The Frog